language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "saved-list-items:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: Zhk8/WC/GmnC9thhml208vsJjATdpPKujLSozYIN3JmejaENGr9tgNuxichCeJTrOahzOoyJXdxN6reY30JHuosNDLVUkgRzSqVmaJRtQuGnfVYk1kQLa3VqNRFkGqQPcXms4Q0SNnfgOBVppJb0n+bl2leggFgc4lERp9l77goFu1eOFhNRXsaVnPfQ17AWQwJ/ZTZm18VRV/QByTHOsszIUwAU2ECzIRU15EfhEGlvafN7EPOltP0vSh0DfanPDBcsOxNb/nj7UcCiYiKDVxei5bHLOVC83vUDJHaT+ggfd9XJB/d413s5oWYTUYpvXek1fJkhD1VTHrkoBfBuaH5vv2gUzW8/Q7B+9s3OS2RjrOY5G+VQfCQsf8NwAKIj8i9ZoqEVpUwGFA+KJLB1Pxl+k8t5gEJsqeVP9uMvdm2slkvc3sRqng/h5Ku2T7ArrAhejgRgCvpW4TnuLpfbsb3EGg/4Z0ixmuCZuw9Oqn6oB6ou8obqnlK6pm1svIRXRa3aTv6Hr9hHOb0MNDGlst3yx01MQ+duoVl1TQofEQqb1kuXP1Ix8xr5F7HZjp1i5nN4j39Cdu0qPFw6bO8GpnxdUeEblNCfE85db51+jD5jQuIHdjcU5mA5g4b+coRmtB3brxgjDxtZ7753XWB/3sZeY4U3K3aNw5x4QCUp+n8=
  - secure: OlItbYGUMDelyeVcFmEFFl9ALjGO8jidd95p/VLpu43m1fueZamOrsy/1iX7MaEXyLzDG3kFSDo1CuBpzwPJs+TCTif3AMm0qhhPoAnsKdPcuuLa7nQIXdNyq5RwPZUmuFqnTy2ZOmzNYmbDKh6mYbBchDVlDVYRJjgsN3SVhwqcKrvqNGWl0UfIrPlvUSnMiObxUBGXGPGv1OMEaFJvVkDhaZgsSfESrPauwjuymBXTHSSDa95CYbpuBKki74F+EXhJszuGDKMEdyVq0aSeIm5GvE5s7kXqtMIstxrkzIrRENdaRlbVEvU2MD/XEJCkjhOcMaexksBWEH3XEJxBBgAwlVHpYGlzFBkvKnLo4mlAJfAh/SbVQ52e2PbPHVBDhfIvfRFkFhtyatX7M4y3QmsypfyxKe4FVNYTFW4YdGyJlzdapvXX6Gx+vxXpyi62lEIaYMpLfSplT4SOMX0nJpP6i3ANuOnDo6zxOTUGTBKM7Az1QjsslYnCx0N62uGE4sC5e1qKWJb6C5L7+K585tED/FcJw9igro018uLUadDnEBaGPNI24YHWPPQ6VL0GXIS5KGq9GHlu2wvGxDNWiJ2SrutJKEJy9nBvO5WtE0FJyoeHoJIMgXJyW3reS5Ebz4A2PSh3rKM44rme3hpuxmH6lKjtgyYfG9ofp13P820=
